# Generated by Django 5.0.1 on 2024-04-29 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="lasst_name",
            new_name="last_name",
        ),
    ]
